version: '3.8'

services:
  db:
    image: postgres:13.3-alpine3.14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
    ports:
      - 5432:5432
    volumes:
      - pgData:/var/lib/postgresql/data
      - ./docker-init-scripts:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:6.2.5-alpine3.14
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server /data/redis.conf
    volumes:
      - redisData:/data
      - ./docker-configs/redis.conf:/data/redis.conf

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    environment:
      # ADMINER_DESIGN: lucas-sandery
      # ADMINER_DESIGN: mvt
      # ADMINER_DESIGN: nette
      ADMINER_DESIGN: pappu687
    ports:
      - 8080:8080

volumes:
  pgData:
  redisData:

