version: '3.8'

services:
  db:
    image: postgres:13.2
    container_name: bingo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
    ports:
      - 5432:5432
    volumes:
      - ../../docker_data/bingo:/var/lib/postgresql/data
      - ./docker-init-scripts:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:6-alpine
    container_name: bingo_redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server /data/redis.conf
    volumes:
      - ../../docker_data/bingo_redis:/data
      - ./docker-configs/redis.conf:/data/redis.conf

  adminer:
    image: adminer
    container_name: bingo_adminer
    restart: always
    ports:
      - 8080:8080

