# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
    ports:
      - 5432:5432
    volumes:
      - ../../docker_data/db_data/data:/var/lib/postgresql/data
      - ./docker-init.d/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

